In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
df = pd.read_csv("Book1.csv")
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [23]:
df.drop('name', axis=1, inplace=True, errors='ignore')

In [28]:
import sklearn

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['origin'] = le.fit_transform(df['origin'])
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,2
1,15.0,8,350.0,165.0,3693,11.5,70,2
2,18.0,8,318.0,150.0,3436,11.0,70,2
3,16.0,8,304.0,150.0,3433,12.0,70,2
4,17.0,8,302.0,140.0,3449,10.5,70,2
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,2
394,44.0,4,97.0,52.0,2130,24.6,82,0
395,32.0,4,135.0,84.0,2295,11.6,82,2
396,28.0,4,120.0,79.0,2625,18.6,82,2
397,31.0,4,119.0,82.0,2720,19.4,82,2

In [33]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [40]:
df.ffill(inplace=True)
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [42]:
x=df.iloc[:,1:8]
y=df[['mpg']]
x

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,2
1,8,350.0,165.0,3693,11.5,70,2
2,8,318.0,150.0,3436,11.0,70,2
3,8,304.0,150.0,3433,12.0,70,2
4,8,302.0,140.0,3449,10.5,70,2
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,2
394,4,97.0,52.0,2130,24.6,82,0
395,4,135.0,84.0,2295,11.6,82,2
396,4,120.0,79.0,2625,18.6,82,2
397,4,119.0,82.0,2720,19.4,82,2

In [43]:
y

      mpg
0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
..    ...
393  27.0
394  44.0
395  32.0
396  28.0
397  31.0

[398 rows x 1 columns]

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
x_train

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
245,4,98.0,66.0,1800,14.4,78,2
110,4,108.0,94.0,2379,16.5,73,1
16,6,199.0,97.0,2774,15.5,70,2
66,8,304.0,150.0,3672,11.5,72,2
153,6,250.0,105.0,3459,16.0,75,2
...,...,...,...,...,...,...,...
71,3,70.0,97.0,2330,13.5,72,1
106,8,350.0,180.0,4499,12.5,73,2
270,4,134.0,95.0,2515,14.8,78,1
348,4,89.0,62.0,2050,17.3,81,1
102,4,97.0,46.0,1950,21.0,73,0

In [47]:
x_test

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
198,4,91.0,53.0,1795,17.4,76,1
396,4,120.0,79.0,2625,18.6,82,2
33,6,232.0,100.0,2634,13.0,71,2
208,8,318.0,150.0,3940,13.2,76,2
93,8,318.0,150.0,4237,14.5,73,2
...,...,...,...,...,...,...,...
378,4,105.0,63.0,2125,14.7,82,2
371,4,135.0,84.0,2525,16.0,82,2
280,6,231.0,115.0,3245,15.4,79,2
323,4,156.0,105.0,2800,14.4,80,2
75,8,318.0,150.0,4077,14.0,72,2

In [48]:
y_train

      mpg
245  36.1
110  22.0
16   18.0
66   17.0
153  18.0
..    ...
71   19.0
106  12.0
270  21.1
348  37.7
102  26.0

[298 rows x 1 columns]

In [49]:
y_test

      mpg
198  33.0
396  28.0
33   19.0
208  13.0
93   14.0
..    ...
378  38.0
371  29.0
280  21.5
323  27.9
75   14.0

[100 rows x 1 columns]